import numpy as np
import time 
import matplotlib.pyplot as plt
import yaml
import os
from pathlib import Path

def read_tir(file_path):
    # Initialize the tirParams dictionary with all parameters set in the MATLAB code
    tir_params = {
        'FILE_TYPE': 'default',
        'FILE_VERSION': 3.0,
        'FILE_FORMAT': 'default',
        'LENGTH': 'default',
        'FORCE': 'default',
        'ANGLE': 'default',
        'MASS': 'default',
        'TIME': 'default',
        'FITTYP': 0,
        'TYRESIDE': 'LEFT',
        'LONGVL': 16.7,
        'VXLOW': 1,
        'ROAD_INCREMENT': 0.01,
        'ROAD_DIRECTION': 1,
        'PROPERTY_FILE_FORMAT': 'default',
        'USER_SUB_ID': 815,
        'N_TIRE_STATES': 4,
        'USE_MODE': 124,
        'HMAX_LOCAL': 2.5E-4,
        'TIME_SWITCH_INTEG': 0.1,
        'UNLOADED_RADIUS': 0.3135,
        'WIDTH': 0.205,
        'ASPECT_RATIO': 0.6,
        'RIM_RADIUS': 0.1905,
        'RIM_WIDTH': 0.152,
        'INFLPRES': 220000,
        'NOMPRES': 220000,
        'MASS1': 9.3,
        'IXX': 0.391,
        'IYY': 0.736,
        'BELT_MASS': 7,
        'BELT_IXX': 0.34,
        'BELT_IYY': 0.6,
        'GRAVITY': -9.81,
        'FNOMIN': 4000,
        'VERTICAL_STIFFNESS': 200000,
        'VERTICAL_DAMPING': 50,
        'MC_CONTOUR_A': 0.5,
        'MC_CONTOUR_B': 0.5,
        'BREFF': 8.4,
        'DREFF': 0.27,
        'FREFF': 0.07,
        'Q_RE0': 1,
        'Q_V1': 0,
        'Q_V2': 0,
        'Q_FZ2': 1.0E-4,
        'Q_FCX': 0,
        'Q_FCY': 0,
        'Q_CAM': 0,
        'PFZ1': 0,
        'BOTTOM_OFFST': 0.01,
        'BOTTOM_STIFF': 2000000,
        'LONGITUDINAL_STIFFNESS': 300000,
        'LATERAL_STIFFNESS': 100000,
        'YAW_STIFFNESS': 5000,
        'FREQ_LONG': 80,
        'FREQ_LAT': 40,
        'FREQ_YAW': 50,
        'FREQ_WINDUP': 70,
        'DAMP_LONG': 0.04,
        'DAMP_LAT': 0.04,
        'DAMP_YAW': 0.04,
        'DAMP_WINDUP': 0.04,
        'DAMP_RESIDUAL': 0.0020,
        'DAMP_VLOW': 0.0010,
        'Q_BVX': 0,
        'Q_BVT': 0,
        'PCFX1': 0,
        'PCFX2': 0,
        'PCFX3': 0,
        'PCFY1': 0,
        'PCFY2': 0,
        'PCFY3': 0,
        'PCMZ1': 0,
        'Q_RA1': 0.5,
        'Q_RA2': 1,
        'Q_RB1': 1,
        'Q_RB2': -1,
        'ELLIPS_SHIFT': 0.8,
        'ELLIPS_LENGTH': 1,
        'ELLIPS_HEIGHT': 1,
        'ELLIPS_ORDER': 1.8,
        'ELLIPS_MAX_STEP': 0.025,
        'ELLIPS_NWIDTH': 10,
        'ELLIPS_NLENGTH': 10,
        'PRESMIN': 10000,
        'PRESMAX': 1000000,
        'FZMIN': 100,
        'FZMAX': 10000,
        'KPUMIN': -1.5,
        'KPUMAX': 1.5,
        'ALPMIN': -1.5,
        'ALPMAX': 1.5,
        'CAMMIN': -0.175,
        'CAMMAX': 0.175,
        'LFZO': 1,
        'LCX': 1,
        'LMUX': 1,
        'LEX': 1,
        'LKX': 1,
        'LHX': 1,
        'LVX': 1,
        'LCY': 1,
        'LMUY': 1,
        'LEY': 1,
        'LKY': 1,
        'LHY': 1,
        'LVY': 1,
        'LTR': 1,
        'LRES': 1,
        'LXAL': 1,
        'LYKA': 1,
        'LVYKA': 1,
        'LS': 1,
        'LKYC': 1,
        'LKZC': 1,
        'LVMX': 1,
        'LMX': 1,
        'LMY': 1,
        'LMP': 1,
        'PCX1': 1.65,
        'PDX1': 1.3,
        'PDX2': -0.15,
        'PDX3': 0,
        'PEX1': 0,
        'PEX2': 0,
        'PEX3': 0,
        'PEX4': 0,
        'PKX1': 20,
        'PKX2': 0,
        'PKX3': 0,
        'PHX1': 0,
        'PHX2': 0,
        'PVX1': 0,
        'PVX2': 0,
        'PPX1': 0,
        'PPX2': 0,
        'PPX3': 0,
        'PPX4': 0,
        'RBX1': 20,
        'RBX2': 15,
        'RBX3': 0,
        'RCX1': 1,
        'REX1': 0,
        'REX2': 0,
        'RHX1': 0,
        'QSX1': 0,
        'QSX2': 0,
        'QSX3': 0,
        'QSX4': 5,
        'QSX5': 1,
        'QSX6': 10,
        'QSX7': 0,
        'QSX8': 0,
        'QSX9': 0.4,
        'QSX10': 0,
        'QSX11': 5,
        'QSX12': 0,
        'QSX13': 0,
        'QSX14': 0,
        'PPMX1': 0,
        'PCY1': 1.3,
        'PDY1': 1.1,
        'PDY2': -0.15,
        'PDY3': 0,
        'PEY1': 0,
        'PEY2': 0,
        'PEY3': 0,
        'PEY4': 0,
        'PEY5': 0,
        'PKY1': -20,
        'PKY2': 1,
        'PKY3': 0,
        'PKY4': 2,
        'PKY5': 0,
        'PKY6': -1,
        'PKY7': 0,
        'PHY1': 0,
        'PHY2': 0,
        'PVY1': 0,
        'PVY2': 0,
        'PVY3': 0,
        'PVY4': 0,
        'PPY1': 0,
        'PPY2': 0,
        'PPY3': 0,
        'PPY4': 0,
        'PPY5': 0,
        'RBY1': 10,
        'RBY2': 10,
        'RBY3': 0,
        'RBY4': 0,
        'RCY1': 1,
        'REY1': 0,
        'REY2': 0,
        'RHY1': 0,
        'RHY2': 0,
        'RVY1': 0,
        'RVY2': 0,
        'RVY3': 0,
        'RVY4': 20,
        'RVY5': 2,
        'RVY6': 10,
        'QSY1': 0.01,
        'QSY2': 0,
        'QSY3': 4.0E-4,
        'QSY4': 4.0E-5,
        'QSY5': 0,
        'QSY6': 0,
        'QSY7': 0.85,
        'QSY8': -0.4,
        'QBZ1': 10,
        'QBZ2': 0,
        'QBZ3': 0,
        'QBZ4': 0,
        'QBZ5': 0,
        'QBZ9': 10,
        'QBZ10': 0,
        'QCZ1': 1.1,
        'QDZ1': 0.12,
        'QDZ2': 0,
        'QDZ3': 0,
        'QDZ4': 0,
        'QDZ6': 0,
        'QDZ7': 0,
        'QDZ8': -0.05,
        'QDZ9': 0,
        'QDZ10': 0,
        'QDZ11': 0,
        'QEZ1': 0,
        'QEZ2': 0,
        'QEZ3': 0,
        'QEZ4': 0,
        'QEZ5': 0,
        'QHZ1': 0,
        'QHZ2': 0,
        'QHZ3': 0,
        'QHZ4': 0,
        'PPZ1': 0,
        'PPZ2': 0,
        'SSZ1': 0,
        'SSZ2': 0,
        'SSZ3': 0,
        'SSZ4': 0,
        'PDXP1': 0.4,
        'PDXP2': 0,
        'PDXP3': 0,
        'PKYP1': 1,
        'PDYP1': 0.4,
        'PDYP2': 0,
        'PDYP3': 0,
        'PDYP4': 0,
        'PHYP1': 1,
        'PHYP2': 0.15,
        'PHYP3': 0,
        'PHYP4': -4,
        'PECP1': 0.5,
        'PECP2': 0,
        'QDTP1': 10,
        'QCRP1': 0.2,
        'QCRP2': 0.1,
        'QBRP1': 0.1,
        'QDRP1': 1,
        'FUNCTION_NAME': 'default',
        'SWITCH_INTEG': 0,
        'Q_FCY2': 0,
        'Q_CAM1': 0,
        'Q_CAM2': 0,
        'Q_CAM3': 0,
        'Q_FYS1': 0,
        'Q_FYS2': 0,
        'Q_FYS3': 0,
        'ENV_C1': 0,
        'ENV_C2': 0,
        'Q_A1': 0,
        'Q_A2': 0,
        'PHY3': 0,
        'PTX1': 0,
        'PTX2': 0,
        'PTX3': 0,
        'PTY1': 0,
        'PTY2': 0,
        'LSGKP': 1,
        'LSGAL': 1,
    }

    # Attempt to open the file
    try:
        with open(file_path, 'r') as file:
            lines = file.readlines()
    except FileNotFoundError:
        raise FileNotFoundError(f"The tire property file located at: '{file_path}' cannot be opened")

    # Process each line in the file
    for line in lines:
        line = line.strip()
        if line and not line.startswith(('$', '!', '[')):
            param, value = line.split('=')[0].strip(), line.split('=')[1].split('$')[0].strip()
            try:
                # Convert to float if possible, except for specific string fields
                if param not in ['FILE_TYPE', 'FILE_FORMAT', 'LENGTH', 'FORCE', 'ANGLE', 'MASS', 'TIME', 'TYRESIDE', 'PROPERTY_FILE_FORMAT']:
                    tir_params[param] = float(value)
                else:
                    tir_params[param] = value
            except ValueError:
                pass  # Skip conversion if the value is not a number
    
    return tir_params

def dump_yaml(tir_params, path, name):
    with open(path + name + '.yaml', 'w') as outfile:
        yaml.dump(tir_params, outfile)
    outfile.close()

script_dir = os.path.dirname(os.path.abspath(__file__))
data_path  = os.path.join(script_dir, 'tire_data', 'TIR_files/')
save_path  = os.path.join(script_dir, 'tire_data', 'yamls/')
filename   = 'example.tir'
TIR_file   = data_path + filename

# Read file and then save to yamls
tir_params = read_tir(TIR_file)
dump_yaml(tir_params, save_path, filename)

